// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivePackage_client.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Broadcast_User;
@class EnterRoomResponse_Statement;
@class RoomCloseBroadcast_Statement;
@class UserInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LivePackageClientRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LivePackageClientRoot : GPBRootObject
@end

#pragma mark - CreateRoomRequest

typedef GPB_ENUM(CreateRoomRequest_FieldNumber) {
  CreateRoomRequest_FieldNumber_Admin = 1,
};

@interface CreateRoomRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *admin;
/** Test to see if @c admin has been set. */
@property(nonatomic, readwrite) BOOL hasAdmin;

@end

#pragma mark - CreateRoomResponse

typedef GPB_ENUM(CreateRoomResponse_FieldNumber) {
  CreateRoomResponse_FieldNumber_Result = 1,
};

@interface CreateRoomResponse : GPBMessage

@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - EnterRoomRequest

typedef GPB_ENUM(EnterRoomRequest_FieldNumber) {
  EnterRoomRequest_FieldNumber_RoomId = 1,
};

@interface EnterRoomRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@end

#pragma mark - UserInfo

typedef GPB_ENUM(UserInfo_FieldNumber) {
  UserInfo_FieldNumber_UserId = 1,
  UserInfo_FieldNumber_Nickname = 2,
  UserInfo_FieldNumber_HeadURL = 3,
};

@interface UserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *headURL;
/** Test to see if @c headURL has been set. */
@property(nonatomic, readwrite) BOOL hasHeadURL;

@end

#pragma mark - EnterRoomResponse

typedef GPB_ENUM(EnterRoomResponse_FieldNumber) {
  EnterRoomResponse_FieldNumber_Result = 1,
  EnterRoomResponse_FieldNumber_UsersArray = 2,
  EnterRoomResponse_FieldNumber_Statement = 3,
  EnterRoomResponse_FieldNumber_Id_p = 4,
  EnterRoomResponse_FieldNumber_LikeTotal = 5,
};

@interface EnterRoomResponse : GPBMessage

@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) EnterRoomResponse_Statement *statement;
/** Test to see if @c statement has been set. */
@property(nonatomic, readwrite) BOOL hasStatement;

/** 系统分配客户端唯一id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite) int64_t likeTotal;

@property(nonatomic, readwrite) BOOL hasLikeTotal;
@end

#pragma mark - EnterRoomResponse_Statement

typedef GPB_ENUM(EnterRoomResponse_Statement_FieldNumber) {
  EnterRoomResponse_Statement_FieldNumber_Online = 1,
};

@interface EnterRoomResponse_Statement : GPBMessage

@property(nonatomic, readwrite) int32_t online;

@property(nonatomic, readwrite) BOOL hasOnline;
@end

#pragma mark - LoginRequest

typedef GPB_ENUM(LoginRequest_FieldNumber) {
  LoginRequest_FieldNumber_Auth = 1,
  LoginRequest_FieldNumber_NickName = 2,
  LoginRequest_FieldNumber_HeadURL = 3,
};

@interface LoginRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *auth;
/** Test to see if @c auth has been set. */
@property(nonatomic, readwrite) BOOL hasAuth;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *headURL;
/** Test to see if @c headURL has been set. */
@property(nonatomic, readwrite) BOOL hasHeadURL;

@end

#pragma mark - LoginResponse

typedef GPB_ENUM(LoginResponse_FieldNumber) {
  LoginResponse_FieldNumber_Result = 1,
};

@interface LoginResponse : GPBMessage

@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - TalkRequest

typedef GPB_ENUM(TalkRequest_FieldNumber) {
  TalkRequest_FieldNumber_Id_p = 1,
  TalkRequest_FieldNumber_Content = 3,
  TalkRequest_FieldNumber_Type = 4,
  TalkRequest_FieldNumber_Time = 5,
};

@interface TalkRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@end

#pragma mark - TalkResponse

typedef GPB_ENUM(TalkResponse_FieldNumber) {
  TalkResponse_FieldNumber_Id_p = 1,
};

@interface TalkResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@end

#pragma mark - Broadcast

typedef GPB_ENUM(Broadcast_FieldNumber) {
  Broadcast_FieldNumber_Id_p = 1,
  Broadcast_FieldNumber_Content = 2,
  Broadcast_FieldNumber_Type = 3,
  Broadcast_FieldNumber_Time = 4,
  Broadcast_FieldNumber_User = 5,
  Broadcast_FieldNumber_ClientId = 9,
  Broadcast_FieldNumber_LikeTotal = 10,
};

@interface Broadcast : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite, strong, null_resettable) Broadcast_User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;
/** Test to see if @c clientId has been set. */
@property(nonatomic, readwrite) BOOL hasClientId;

@property(nonatomic, readwrite) int64_t likeTotal;

@property(nonatomic, readwrite) BOOL hasLikeTotal;
@end

#pragma mark - Broadcast_User

typedef GPB_ENUM(Broadcast_User_FieldNumber) {
  Broadcast_User_FieldNumber_UserId = 6,
  Broadcast_User_FieldNumber_NickName = 7,
  Broadcast_User_FieldNumber_HeadURL = 8,
};

@interface Broadcast_User : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *headURL;
/** Test to see if @c headURL has been set. */
@property(nonatomic, readwrite) BOOL hasHeadURL;

@end

#pragma mark - CloseRoomRequest

typedef GPB_ENUM(CloseRoomRequest_FieldNumber) {
  CloseRoomRequest_FieldNumber_RoomId = 1,
  CloseRoomRequest_FieldNumber_Reason = 2,
};

@interface CloseRoomRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite) int32_t reason;

@property(nonatomic, readwrite) BOOL hasReason;
@end

#pragma mark - CloseRoomResponse

typedef GPB_ENUM(CloseRoomResponse_FieldNumber) {
  CloseRoomResponse_FieldNumber_Result = 1,
};

@interface CloseRoomResponse : GPBMessage

@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - RoomCloseBroadcast

typedef GPB_ENUM(RoomCloseBroadcast_FieldNumber) {
  RoomCloseBroadcast_FieldNumber_Statement = 1,
  RoomCloseBroadcast_FieldNumber_Reason = 2,
};

@interface RoomCloseBroadcast : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomCloseBroadcast_Statement *statement;
/** Test to see if @c statement has been set. */
@property(nonatomic, readwrite) BOOL hasStatement;

@property(nonatomic, readwrite) int32_t reason;

@property(nonatomic, readwrite) BOOL hasReason;
@end

#pragma mark - RoomCloseBroadcast_Statement

typedef GPB_ENUM(RoomCloseBroadcast_Statement_FieldNumber) {
  RoomCloseBroadcast_Statement_FieldNumber_LikeTotal = 1,
  RoomCloseBroadcast_Statement_FieldNumber_PostsTotal = 2,
  RoomCloseBroadcast_Statement_FieldNumber_OnlineTotal = 3,
  RoomCloseBroadcast_Statement_FieldNumber_Duration = 4,
};

@interface RoomCloseBroadcast_Statement : GPBMessage

@property(nonatomic, readwrite) int64_t likeTotal;

@property(nonatomic, readwrite) BOOL hasLikeTotal;
@property(nonatomic, readwrite) int64_t postsTotal;

@property(nonatomic, readwrite) BOOL hasPostsTotal;
@property(nonatomic, readwrite) int32_t onlineTotal;

@property(nonatomic, readwrite) BOOL hasOnlineTotal;
@property(nonatomic, readwrite) int32_t duration;

@property(nonatomic, readwrite) BOOL hasDuration;
@end

#pragma mark - MakeUserSilenceRequest

typedef GPB_ENUM(MakeUserSilenceRequest_FieldNumber) {
  MakeUserSilenceRequest_FieldNumber_UserId = 1,
};

@interface MakeUserSilenceRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
